name: "cleanup old builds"

on:
  schedule:
    - cron: '14 1 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  cleanup:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4.1.1"
      - name: "setup python ${{ env.PYTHON_VERSION }}"
        uses: "actions/setup-python@v5.0.0"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: "pip"
          cache-dependency-path: "_scripts/requirements.txt"
      - name: "install dependencies"
        run: "pip install -r _scripts/requirements.txt"
      - name: "cleanup old PRs" 
        run: |
          git config user.name "kyoripowered-deployment[bot]"
          git config user.email "121842021+kyoripowered-deployment[bot]@users.noreply.github.com"
          python _scripts/cleanup.py .
          git commit -a -m 'cleanup outdated previews' || true
          git push 
